### ISSUE TITLE
Automatic generated speech of Audio Description text overlaps Audio Description that is in the video

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#186] opened 2019-08-06 20:32 UTC
On [a Perspectives Video page](https://www.w3.org/WAI/perspective-videos/customizable/), if I click "Enable Audio Description" button, I get the audio described version of the video, and see the text of the audio description (good!), *and* it is read aloud - overlapping with the audio in the video.

I'm guessing this is due to new features in the player since we set up those pages.

I'm happy to talk through options with the new version...

**Comment by yatil** [comment] 2019-08-07 05:07
Thanks for describing the issue so well, I can see it and hope to fix it today. 😲

**Comment by yatil** [comment] 2019-08-07 06:41
Hm. I had a look and it looks like it is impossible to switch off the automatic reading of the descriptions. Alternatively if I specify an audio described video, it seems to not display the audio description then. It is also not possible to specify a different caption file specifically for the audio described version, which means either the transcript or the caption is out of sync with the video (as the player expects AD and non-AD video to be the same length).

Maybe @terrill has an idea how to tackle this.

**Comment by terrill** [comment] 2019-08-08 15:39
@yatil Able Player supports audio description either of two ways: 
1.  A separate audio described version of the video
2. Text-based description in a WebVTT file. 

You shouldn't use both simultaneously. If you do, users get redundant audio description text. This is the same as it's always been, but prior to Able Player v4.0 users only heard description text if they're using screen readers. With v4.0 and higher, the description text is read by browsers if they support the Web Speech API. Users who don't want to hear this can toggle it off using the Descriptions button on the player control bar. 

Unfortunately, if you opt for Method 1 rather than Method 2, description text isn't displayed visibly, nor is it parsed and included in the interactive transcript. 

A solution on our end would be to add an attribute to Able Player, something like **data-description-audible**, which would be true by default. For your use case, where you want the non-audible benefits of WebVTT audio description (visible text, and included in the transcript), but don't want the description text to be voiced, you could set that attribute to false.  Does that seem feasible?  If so, I can add it as a high priority feature request.

**Comment by yatil** [comment] 2019-08-08 16:01
@Terrill I think that would be a good solution. I like the visual distinction between the captions and the audio description text, especially in the transcript. One could argue that subtitling the audio description should be done in the actual captions! In our uses case. And while that feels kinda right, I think having the two use cases separated makes som kind of sense. 

Thanks for looking into this!

**Comment by terrill** [comment] 2019-08-12 21:02
@yatil Able Player v4.0.10 (the latest commit pushed to [the develop branch](https://github.com/ableplayer/ableplayer/commits/develop) should address this issue). I decided not to add a new attribute as described in my previous comment. Instead: 

- If audio description is provided using both methods (separate described video *and* WebVTT description track), then the descriptions are always delivered using the separate described video, *not* using synthesized speech. 
- The WebVTT file is always used to display the description text, if users have "Make description visible" in their Description Preferences dialog. 
- The WebVTT file is always used to incorporate description text into the auto-generated transcript. 
- If users have "Automatically pause video when description starts" checked in their Description Preferences dialog, this only works if description is being delivered with synthesized speech, *not* if it's being delivered with a separate video. 

Let me know if you spot any lingering problems.

**Comment by yatil** [comment] 2019-08-13 10:03
@terrill Thank you very much, I’ll update to the development branch and see if it fixes it.

**Comment by yatil** [comment] 2019-08-13 10:39
@terrill This seems to be not working for us and I guess the reason is that we are using two players to display the non-AD and the AD file, see:

To reproduce:

1. Go to https://deploy-preview-21--wai-perspective-videos.netlify.com/perspective-videos/keyboard/
2. Click on the green-ich button ”enable audio description”.
3. Click the Audio Description button on the player.
4. Click Play.

I think our configuration is somehow wrong. I couldn’t get the different VTT files for captions to sync up when the non-AD and AD videos have _different lengths_. Also we are embedding through youtube, which might be a reason why it is not working.

Here’s the configuration we are using: 

```
<div class="video-container" data-video-type="" dir="ltr">
  <video preload="metadata" 
         data-youtube-id="93UgG72os8M" 
         data-youtube-nocookie="true" 
         width="450">
    <track src="/perspective-videos/cc/keyboard-en.vtt" 
           label="English" kind="captions" srclang="en">
  </video>
</div>

<div class="video-container" data-video-type="audio-described">
  <video preload="metadata" 
         data-youtube-id="1rBwxGMT9ZM" 
        data-youtube-nocookie="true" 
        width="450">
    <track src="/perspective-videos/cc/keyboard_ad-en.vtt" 
           label="English" kind="captions" srclang="en">
    <track src="/perspective-videos/cc/keyboard_ad_desc-en.vtt"
           label="English" kind="descriptions" srclang="en">
  </video>
</div>
<p><button id="audio_description_button"><svg aria-hidden="true" class="icon-audio-description "><use xlink:href="/assets/images/icons.svg#icon-audio-description"></use></svg> <span>Enable Audio Description</span></button></p>
```

Thanks for all the work you do, @terrill, it is a really complex piece of software to maintain.

**Comment by terrill** [comment] 2019-08-13 23:19
Ah, I see. Since your source file for the described version is identified with the `data-youtube-id` attribute rather than the `data-youtube-desc-id`, Able Player doesn't recognize it as a described version. Therefore it thinks the WebVTT descriptions are the **only** descriptions available, and verbalizes them. I guess I'll have to add a **data-description-audible** attribute after all, as proposed in my earlier comment. Stay tuned... 

Also, since you have a separate "Enable audio description" button on your site, do you need a "D" button on the Able Player controller?  Seems to me that having two buttons with similar purposes is likely to cause confusion.  You *should* be able to eliminate the "D" button by adding `data-use-descriptions-buttton="false"` to the `<video>` element.  That doesn't seem to be working at the moment, but I'll fix it shortly. 

And once users have clicked your "Enable Audio Description" button, the button text should change to "Disable Audio Description", yes? If that's the intention, it doesn't seem to be working currently.

**Comment by terrill** [comment] 2019-08-14 00:12
OK @yatil v4.0.11 now supports **data-description-audible**. 

If you add `data-description-audible="false"` to the `<video>` element, that should prevent the browser or screen readers from reading the description, but you'll still have visible description text, and description will be integrated into the transcript. 

If you also add `data-use-descriptions-button="false"` to the `<video>` element,  that will eliminate the "D" button from the player control bar.

**Comment by yatil** [comment] 2019-08-14 10:36
@terrill Thank you very much!

> Also, since you have a separate "Enable audio description" button on your site, do you need a "D" button on the Able Player controller? Seems to me that having two buttons with similar purposes is likely to cause confusion. You can eliminate the "D" button by adding data-use-descriptions-buttton="false" to the <video> element.

I think we want users to have the option to see “captions” for the Audio Descriptions as well, so that’s where the “D” button is useful.

> And once users have clicked your "Enable Audio Description" button, the button text should change to "Disable Audio Description", yes? If that's the intention, it doesn't seem to be working currently.

Hm. It works on the [published website](https://www.w3.org/WAI/perspective-videos/contrast/). I’ll double check. Thanks for pointing it out.

> OK @yatil v4.0.11 now supports data-description-audible.

This is great, thank you very much! I’ll implement it soon!

**Closed** 2019-08-14 11:13 UTC
Labels: bug
